import { LanguageCode } from "@/lib/i18n";

export type LocalizedText = Record<LanguageCode, string>;

export type ItineraryProfile = "car" | "motorcycle" | "both";

export type ClubItinerary = {
  id: string;
  profile: ItineraryProfile;
  title: LocalizedText;
  strapline: LocalizedText;
  rhythm: LocalizedText;
  duration: string;
  distance: string;
  bestSeason: LocalizedText;
  start: string;
  finish: string;
  waypoints: string[];
  highlights: LocalizedText[];
  bmwAngle: LocalizedText;
  notes: LocalizedText[];
};

export const itineraryGuide: ClubItinerary[] = [
  {
    id: "grand-tour-central",
    profile: "car",
    title: {
      ca: "Grand Tour central: Engolasters, Canillo i Coll d’Ordino",
      es: "Grand Tour central: Engolasters, Canillo y Coll d’Ordino",
      fr: "Grand Tour central : Engolasters, Canillo et Coll d’Ordino",
      en: "Central Grand Tour: Engolasters, Canillo and Coll d’Ordino",
      pt: "Grand Tour central: Engolasters, Canillo e Coll d’Ordino",
      de: "Zentrale Grand Tour: Engolasters, Canillo und Coll d’Ordino",
      ru: "Центральный Grand Tour: Engolasters, Canillo и Coll d’Ordino",
    },
    strapline: {
      ca: "Ruta elegant de cotxe per a un BMW touring, amb miradors, vall oberta i una conducció fluida.",
      es: "Ruta elegante de coche para un BMW touring, con miradores, valle abierto y una conducción fluida.",
      fr: "Itinéraire élégant en voiture pour un BMW touring, avec belvédères, vallée ouverte et conduite fluide.",
      en: "Elegant car route for a BMW touring setup, with viewpoints, open valleys and fluid driving.",
      pt: "Rota elegante de carro para um BMW touring, com miradouros, vale aberto e condução fluida.",
      de: "Elegante Autoroute für einen BMW Touring mit Aussichtspunkten, offenem Tal und flüssigem Fahren.",
      ru: "Элегантный автомобильный маршрут для BMW touring: смотровые, открытые долины и плавный темп.",
    },
    rhythm: {
      ca: "Fluïda",
      es: "Fluida",
      fr: "Fluide",
      en: "Flowing",
      pt: "Fluida",
      de: "Flüssig",
      ru: "Плавный ритм",
    },
    duration: "2.5-3.5 h",
    distance: "55-70 km",
    bestSeason: {
      ca: "Primavera, estiu i tardor",
      es: "Primavera, verano y otoño",
      fr: "Printemps, été et automne",
      en: "Spring, summer and autumn",
      pt: "Primavera, verão e outono",
      de: "Frühling, Sommer und Herbst",
      ru: "Весна, лето и осень",
    },
    start: "Andorra la Vella",
    finish: "Ordino / Andorra la Vella",
    waypoints: ["Andorra la Vella", "Escaldes-Engordany", "Engolasters", "Canillo", "Meritxell", "Ordino", "Coll d’Ordino"],
    highlights: [
      {
        ca: "Comença suaument pujant cap a Engolasters per obrir la ruta amb vistes sobre la vall central.",
        es: "Empieza suave subiendo hacia Engolasters para abrir la ruta con vistas sobre el valle central.",
        fr: "Commencez en douceur par Engolasters pour ouvrir la route avec vue sur la vallée centrale.",
        en: "Start gently by climbing towards Engolasters to open the route with views over the central valley.",
        pt: "Começa suave subindo para Engolasters para abrir a rota com vistas sobre o vale central.",
        de: "Beginnt sanft Richtung Engolasters und öffnet die Route mit Blicken über das zentrale Tal.",
        ru: "Начинается мягким подъёмом к Engolasters с видами на центральную долину.",
      },
      {
        ca: "Continua per Canillo i Meritxell abans de rematar amb el mirador del Coll d’Ordino.",
        es: "Sigue por Canillo y Meritxell antes de rematar con el mirador del Coll d’Ordino.",
        fr: "Poursuivez par Canillo et Meritxell avant de terminer au belvédère du Coll d’Ordino.",
        en: "Continue through Canillo and Meritxell before finishing at the Coll d’Ordino viewpoint.",
        pt: "Segue por Canillo e Meritxell antes de terminar no miradouro do Coll d’Ordino.",
        de: "Weiter über Canillo und Meritxell, bevor die Route am Aussichtspunkt Coll d’Ordino endet.",
        ru: "Далее через Canillo и Meritxell к финальному виду с Coll d’Ordino.",
      },
    ],
    bmwAngle: {
      ca: "Perfecta per a Sèrie 3, Sèrie 5, Z4 o qualsevol BMW orientat a carretera fina i gaudi panoràmic.",
      es: "Perfecta para Serie 3, Serie 5, Z4 o cualquier BMW orientado a carretera fina y disfrute panorámico.",
      fr: "Parfaite pour une Série 3, Série 5, Z4 ou tout BMW pensé pour la route fluide et le panorama.",
      en: "Perfect for a 3 Series, 5 Series, Z4 or any BMW built for refined road driving and panoramic enjoyment.",
      pt: "Perfeita para Série 3, Série 5, Z4 ou qualquer BMW voltado para estrada refinada e prazer panorâmico.",
      de: "Perfekt für 3er, 5er, Z4 oder jeden BMW mit Fokus auf feine Landstraße und Panorama.",
      ru: "Идеальна для 3 Series, 5 Series, Z4 и любого BMW для красивой дорожной езды.",
    },
    notes: [
      {
        ca: "A l’hivern, comprova l’accés al Coll d’Ordino: la carretera pot no ser practicable per neu acumulada.",
        es: "En invierno, comprueba el acceso al Coll d’Ordino: la carretera puede no ser practicable por nieve acumulada.",
        fr: "En hiver, vérifiez l’accès au Coll d’Ordino : la route peut devenir impraticable en raison de la neige.",
        en: "In winter, check access to Coll d’Ordino: the road may become impractical because of accumulated snow.",
        pt: "No inverno, verifica o acesso ao Coll d’Ordino: a estrada pode ficar impraticável devido à neve.",
        de: "Im Winter Zugang zum Coll d’Ordino prüfen: die Straße kann wegen Schnee unpassierbar sein.",
        ru: "Зимой проверь доступ к Coll d’Ordino: дорога может быть непроходимой из-за снега.",
      },
      {
        ca: "Si vas amb BMW elèctric, tens punts útils a Escaldes, Ordino i la zona d’Arcalís.",
        es: "Si vas con BMW eléctrico, tienes puntos útiles en Escaldes, Ordino y la zona de Arcalís.",
        fr: "Si vous allez en BMW électrique, vous avez des points utiles à Escaldes, Ordino et vers Arcalís.",
        en: "If you go in an electric BMW, useful charging points exist in Escaldes, Ordino and the Arcalís area.",
        pt: "Se fores com um BMW elétrico, tens pontos úteis em Escaldes, Ordino e na zona de Arcalís.",
        de: "Mit einem elektrischen BMW helfen Ladepunkte in Escaldes, Ordino und Richtung Arcalís.",
        ru: "Для BMW i полезны зарядки в Escaldes, Ordino и в зоне Arcalís.",
      },
    ],
  },
  {
    id: "west-viewpoints-loop",
    profile: "both",
    title: {
      ca: "Loop oest: La Massana, Pal i Coll de la Botella",
      es: "Loop oeste: La Massana, Pal y Coll de la Botella",
      fr: "Boucle ouest : La Massana, Pal et Coll de la Botella",
      en: "Western loop: La Massana, Pal and Coll de la Botella",
      pt: "Loop oeste: La Massana, Pal e Coll de la Botella",
      de: "Westschleife: La Massana, Pal und Coll de la Botella",
      ru: "Западная петля: La Massana, Pal и Coll de la Botella",
    },
    strapline: {
      ca: "Una ruta molt BMW per gaudir del xassís: revolts nets, miradors potents i retorn amb molt ritme.",
      es: "Una ruta muy BMW para disfrutar del chasis: curvas limpias, miradores potentes y regreso con mucho ritmo.",
      fr: "Une route très BMW pour profiter du châssis : virages propres, belvédères puissants et retour rythmé.",
      en: "A very BMW route to enjoy the chassis: clean curves, strong viewpoints and a rhythm-filled return.",
      pt: "Uma rota muito BMW para desfrutar do chassis: curvas limpas, miradouros fortes e regresso com ritmo.",
      de: "Eine sehr BMW-artige Route für Fahrwerkspaß: saubere Kurven, starke Aussichtspunkte und rhythmische Rückkehr.",
      ru: "Очень BMW-маршрут: чистые повороты, сильные виды и приятный ритм назад.",
    },
    rhythm: {
      ca: "Dinàmica",
      es: "Dinámica",
      fr: "Dynamique",
      en: "Dynamic",
      pt: "Dinâmica",
      de: "Dynamisch",
      ru: "Динамичный",
    },
    duration: "2-3 h",
    distance: "45-60 km",
    bestSeason: {
      ca: "Final de primavera a tardor",
      es: "Final de primavera a otoño",
      fr: "Fin du printemps à l’automne",
      en: "Late spring to autumn",
      pt: "Final da primavera ao outono",
      de: "Spätfrühling bis Herbst",
      ru: "С конца весны до осени",
    },
    start: "La Massana",
    finish: "La Massana / Ordino",
    waypoints: ["La Massana", "Pal", "Coll de la Botella", "Arinsal", "Erts", "Ordino"],
    highlights: [
      {
        ca: "Puja cap a Pal i regala’t la parada forta del mirador del Coll de la Botella.",
        es: "Sube hacia Pal y regálate la parada fuerte del mirador del Coll de la Botella.",
        fr: "Montez vers Pal et offrez-vous l’arrêt fort au belvédère du Coll de la Botella.",
        en: "Climb towards Pal and make the strong stop at the Coll de la Botella viewpoint.",
        pt: "Sobe para Pal e faz a paragem forte no miradouro do Coll de la Botella.",
        de: "Fahrt Richtung Pal und nehmt den starken Stopp am Aussichtspunkt Coll de la Botella mit.",
        ru: "Поднимайтесь к Pal и делайте сильную остановку у Mirador Coll de la Botella.",
      },
      {
        ca: "Baixa després per Arinsal i Erts per tancar una ruta curta però molt agraïda.",
        es: "Baja después por Arinsal y Erts para cerrar una ruta corta pero muy agradecida.",
        fr: "Redescendez ensuite par Arinsal et Erts pour fermer une sortie courte mais très satisfaisante.",
        en: "Drop back through Arinsal and Erts to complete a short but deeply rewarding run.",
        pt: "Desce depois por Arinsal e Erts para fechar uma saída curta mas muito gratificante.",
        de: "Danach über Arinsal und Erts zurück für eine kurze, aber sehr lohnende Runde.",
        ru: "Спуск через Arinsal и Erts завершает короткий, но очень благодарный маршрут.",
      },
    ],
    bmwAngle: {
      ca: "Ideal tant per a un BMW compacte o M Performance com per a una GS o una RT si vols una sortida curta i intensa.",
      es: "Ideal tanto para un BMW compacto o M Performance como para una GS o una RT si quieres una salida corta e intensa.",
      fr: "Idéal autant pour une BMW compacte ou M Performance que pour une GS ou une RT si vous cherchez une sortie courte et intense.",
      en: "Ideal for a compact BMW or M Performance car, and equally good for a GS or RT if you want a short intense outing.",
      pt: "Ideal tanto para um BMW compacto ou M Performance como para uma GS ou RT se queres uma saída curta e intensa.",
      de: "Ideal für einen kompakten BMW oder M Performance und genauso gut für GS oder RT bei kurzer intensiver Ausfahrt.",
      ru: "Подходит и для компактного BMW/M Performance, и для GS или RT, если хочется короткой яркой вылазки.",
    },
    notes: [
      {
        ca: "És una ruta molt bona per matí o tarda curta, sense necessitat de convertir-la en excursió de dia sencer.",
        es: "Es una ruta muy buena para mañana o tarde corta, sin necesidad de convertirla en excursión de día entero.",
        fr: "Très bonne route pour une matinée ou une courte après-midi, sans necesidad de la convertir en journée complète.",
        en: "A great morning or short afternoon route without turning it into a full-day excursion.",
        pt: "É uma rota muito boa para manhã ou tarde curta, sem a transformar em excursão de dia inteiro.",
        de: "Sehr gut für einen Morgen oder kurzen Nachmittag, ohne gleich einen ganzen Tag daraus zu machen.",
        ru: "Отличный вариант на утро или короткий вечер без необходимости тратить весь день.",
      },
    ],
  },
  {
    id: "envalira-high-mountain",
    profile: "motorcycle",
    title: {
      ca: "Alta muntanya: Encamp, Pas de la Casa i Port d’Envalira",
      es: "Alta montaña: Encamp, Pas de la Casa y Port d’Envalira",
      fr: "Haute montagne : Encamp, Pas de la Casa et Port d’Envalira",
      en: "High mountain run: Encamp, Pas de la Casa and Port d’Envalira",
      pt: "Alta montanha: Encamp, Pas de la Casa e Port d’Envalira",
      de: "Hochgebirge: Encamp, Pas de la Casa und Port d’Envalira",
      ru: "Высокогорный маршрут: Encamp, Pas de la Casa и Port d’Envalira",
    },
    strapline: {
      ca: "La ruta més alpina del paquet: sensació de coll gran, paisatge més dur i ADN de moto claríssim.",
      es: "La ruta más alpina del paquete: sensación de puerto grande, paisaje más duro y ADN de moto clarísimo.",
      fr: "La plus alpine du lot : sensation de grand col, paysage plus rude et ADN moto très clair.",
      en: "The most alpine route of the set: big-pass feeling, harsher scenery and unmistakable motorcycle DNA.",
      pt: "A mais alpina do conjunto: sensação de grande porto, paisagem mais dura e ADN de moto claríssimo.",
      de: "Die alpinste Route im Paket: großes-Pass-Gefühl, härtere Landschaft und klare Motorrad-DNA.",
      ru: "Самый альпийский маршрут: ощущение большого перевала, суровый пейзаж и яркая мото-ДНК.",
    },
    rhythm: {
      ca: "Alpina",
      es: "Alpina",
      fr: "Alpine",
      en: "Alpine",
      pt: "Alpina",
      de: "Alpin",
      ru: "Альпийский",
    },
    duration: "2.5-4 h",
    distance: "60-85 km",
    bestSeason: {
      ca: "Estiu i inicis de tardor",
      es: "Verano e inicios de otoño",
      fr: "Été et début d’automne",
      en: "Summer and early autumn",
      pt: "Verão e início do outono",
      de: "Sommer und Frühherbst",
      ru: "Лето и ранняя осень",
    },
    start: "Encamp",
    finish: "Pas de la Casa / Encamp",
    waypoints: ["Encamp", "Grau Roig", "Pas de la Casa", "Port d’Envalira", "Andorra Circuit"],
    highlights: [
      {
        ca: "Des de Encamp cap a Pas de la Casa la carretera canvia de to i entra en lectura d’alta muntanya.",
        es: "Desde Encamp hacia Pas de la Casa la carretera cambia de tono y entra en lectura de alta montaña.",
        fr: "Depuis Encamp vers Pas de la Casa, la route change de ton et prend une vraie lecture haute montagne.",
        en: "From Encamp to Pas de la Casa the road changes character and becomes true high-mountain driving.",
        pt: "De Encamp até Pas de la Casa a estrada muda de tom e entra em modo alta montanha.",
        de: "Von Encamp Richtung Pas de la Casa wechselt der Charakter in echtes Hochgebirgsfahren.",
        ru: "От Encamp к Pas de la Casa дорога резко переходит в настоящую высокогорную подачу.",
      },
      {
        ca: "El pas per Envalira i l’entorn del Circuit d’Andorra donen un final molt potent per a moto o roadster.",
        es: "El paso por Envalira y el entorno del Circuit d’Andorra dan un final muy potente para moto o roadster.",
        fr: "Le passage par Envalira et l’environnement du Circuit d’Andorra offrent une fin très forte pour moto ou roadster.",
        en: "Envalira and the Andorra Circuit surroundings make for a powerful finale for a bike or roadster.",
        pt: "A passagem por Envalira e o ambiente do Circuit d’Andorra dão um final muito forte para moto ou roadster.",
        de: "Envalira und das Umfeld des Andorra Circuit liefern ein starkes Finale für Motorrad oder Roadster.",
        ru: "Участок Envalira и зона Andorra Circuit дают очень мощный финал для мотоцикла или родстера.",
      },
    ],
    bmwAngle: {
      ca: "Especialment bona per BMW Motorrad, però també per Z4, M240i o qualsevol cotxe que gaudeixi de cota, respiració i paisatge obert.",
      es: "Especialmente buena para BMW Motorrad, pero también para Z4, M240i o cualquier coche que disfrute de altura, respiración y paisaje abierto.",
      fr: "Particulièrement bonne pour BMW Motorrad, mais aussi pour un Z4, M240i ou toute voiture aimant l’altitude et l’ouverture.",
      en: "Especially good for BMW Motorrad, but also for a Z4, M240i or any car that loves altitude, breathing room and open scenery.",
      pt: "Especialmente boa para BMW Motorrad, mas também para Z4, M240i ou qualquer carro que goste de altitude e paisagem aberta.",
      de: "Besonders gut für BMW Motorrad, aber auch für Z4, M240i oder jedes Auto, das Höhe und offene Landschaft liebt.",
      ru: "Особенно хорош для BMW Motorrad, но также для Z4, M240i и любых машин, любящих высоту и открытые виды.",
    },
    notes: [
      {
        ca: "És la més sensible al temps: vent, fred o boira poden canviar molt l’experiència.",
        es: "Es la más sensible al tiempo: viento, frío o niebla pueden cambiar mucho la experiencia.",
        fr: "C’est la plus sensible à la météo : vent, froid ou brouillard peuvent beaucoup changer l’expérience.",
        en: "This is the most weather-sensitive route: wind, cold or fog can change the experience a lot.",
        pt: "É a mais sensível ao tempo: vento, frio ou nevoeiro mudam muito a experiência.",
        de: "Die Route ist am empfindlichsten fürs Wetter: Wind, Kälte oder Nebel verändern das Erlebnis stark.",
        ru: "Это самый погодозависимый маршрут: ветер, холод и туман сильно меняют впечатление.",
      },
    ],
  },
  {
    id: "ordino-tristaina-touring",
    profile: "both",
    title: {
      ca: "Touring nord: Ordino, La Cortinada, El Serrat i Arcalís",
      es: "Touring norte: Ordino, La Cortinada, El Serrat y Arcalís",
      fr: "Touring nord : Ordino, La Cortinada, El Serrat et Arcalís",
      en: "Northern touring: Ordino, La Cortinada, El Serrat and Arcalís",
      pt: "Touring norte: Ordino, La Cortinada, El Serrat e Arcalís",
      de: "Nord-Touring: Ordino, La Cortinada, El Serrat und Arcalís",
      ru: "Северный touring: Ordino, La Cortinada, El Serrat и Arcalís",
    },
    strapline: {
      ca: "Ruta de vall i cota, més serena, ideal per combinar conducció, fotografia i alguna parada tranquil·la.",
      es: "Ruta de valle y altura, más serena, ideal para combinar conducción, fotografía y alguna parada tranquila.",
      fr: "Route de vallée et d’altitude, plus sereine, idéale pour combiner conduite, photo et arrêts tranquilles.",
      en: "A calmer valley-and-altitude route, ideal for combining driving, photography and relaxed stops.",
      pt: "Rota de vale e altitude, mais serena, ideal para combinar condução, fotografia e paragens tranquilas.",
      de: "Ruhigere Tal- und Höhenroute, ideal für Fahren, Fotografie und entspannte Stopps.",
      ru: "Более спокойный маршрут долина-высота: для вождения, фото и размеренных остановок.",
    },
    rhythm: {
      ca: "Touring",
      es: "Touring",
      fr: "Touring",
      en: "Touring",
      pt: "Touring",
      de: "Touring",
      ru: "Туринговый",
    },
    duration: "3-4.5 h",
    distance: "55-75 km",
    bestSeason: {
      ca: "Estiu i tardor clara",
      es: "Verano y otoño claro",
      fr: "Été et bel automne",
      en: "Summer and clear autumn days",
      pt: "Verão e outono limpo",
      de: "Sommer und klarer Herbst",
      ru: "Лето и ясная осень",
    },
    start: "Ordino",
    finish: "Arcalís / Ordino",
    waypoints: ["Ordino", "La Cortinada", "Arans", "El Serrat", "Arcalís"],
    highlights: [
      {
        ca: "És la ruta que millor encaixa si vols vendre Andorra com a destinació premium de carretera i paisatge.",
        es: "Es la ruta que mejor encaja si quieres vender Andorra como destino premium de carretera y paisaje.",
        fr: "C’est la route qui colle le mieux si l’on veut vendre l’Andorre comme destination premium de route et paysage.",
        en: "This is the route that best sells Andorra as a premium road-and-landscape destination.",
        pt: "É a rota que melhor encaixa se queres vender Andorra como destino premium de estrada e paisagem.",
        de: "Das ist die Route, die Andorra am besten als Premium-Ziel für Straße und Landschaft erzählt.",
        ru: "Это маршрут, который лучше всего продаёт Андорру как премиальное направление для дороги и пейзажа.",
      },
      {
        ca: "Va pujant de poble en poble fins arribar a un final d’alta vall molt net visualment.",
        es: "Va subiendo de pueblo en pueblo hasta llegar a un final de alta valle muy limpio visualmente.",
        fr: "Elle monte de village en village jusqu’à une fin de haute vallée très propre visuellement.",
        en: "It climbs village by village until it reaches a visually clean high-valley finish.",
        pt: "Vai subindo de aldeia em aldeia até chegar a um final de vale alto muito limpo visualmente.",
        de: "Sie steigt von Dorf zu Dorf bis zu einem visuell sehr klaren Hoch-Tal-Finale.",
        ru: "Маршрут поднимается от деревни к деревне к очень чистому визуально финалу высокой долины.",
      },
    ],
    bmwAngle: {
      ca: "Molt bona per a un BMW GS, RT, touring dièsel o híbrid, i també per fer fotos i contingut de club sense pressa.",
      es: "Muy buena para una BMW GS, RT, touring diésel o híbrido, y también para hacer fotos y contenido de club sin prisa.",
      fr: "Très bonne pour une BMW GS, RT, touring diesel ou hybride, et aussi pour créer du contenu de club sans prisas.",
      en: "Excellent for a BMW GS, RT, diesel or hybrid touring car, and also for relaxed club photography and content.",
      pt: "Muito boa para uma BMW GS, RT, touring diesel ou híbrido, e também para fotos e conteúdo de clube sem pressa.",
      de: "Sehr gut für BMW GS, RT, Diesel- oder Hybrid-Touring und ebenso für entspannte Club-Fotos und Content.",
      ru: "Отлична для BMW GS, RT, дизельного или гибридного touring, а также для фото и контента клуба без спешки.",
    },
    notes: [
      {
        ca: "És una gran candidata per a sortida oficial del club amb esmorzar, parades i cotxes ben presentats.",
        es: "Es una gran candidata para salida oficial del club con desayuno, paradas y coches bien presentados.",
        fr: "Excellente candidate pour une sortie officielle du club avec desayuno, arrêts et voitures bien présentées.",
        en: "A strong candidate for an official club outing with breakfast stops and well-presented cars.",
        pt: "É uma grande candidata para saída oficial do clube com pequeno-almoço, paragens e carros bem apresentados.",
        de: "Ein starker Kandidat für eine offizielle Club-Ausfahrt mit Frühstücksstopp und gut präsentierten Autos.",
        ru: "Отличный кандидат на официальную вылазку клуба с завтраком, остановками и красивой подачей машин.",
      },
    ],
  },
];
